manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Chatblanc77
      url-base: https://github.com/Chatblanc77
  projects:
    - name: zmk
      remote: Chatblanc77
      revision: oled-ext-pwr
      import: app/west.yml
  self:
    path: config
